# ------------------------------------------------------------------
#                  ____        _            _
#                 |  _ \ _   _| |_ ___ _ __| | __
#                 | |_) | | | | __/ _ \ '__| |/ /
#                 |  __/| |_| | ||  __/ |  |   <
#                 |_|    \__, |\__\___|_|  |_|\_\
#                        |___/                        Settings file
# ------------------------------------------------------------------
# Python Iterator for Kfold and co. - pjluc 2021
#
# This is a sample configuration
# 
# Note : Afin d'être portable, le paramètre datasets_dir peut être
#        forcé via une variable d'environnement.

global:
    description: Test of neural network architectures for regression models.
    settings v.: 1.0
    seed: 123
    datasets_dir: ./
    run_dir: ./ModelAssessment/NN_r
    

datasets:
    
    compo_E_wo_outliers:
        filename: Compo_E_wo_outlier.csv
        columns_x: ['Zr_at','Nb_at','Mo_at','Ti_at','Cr_at']
        columns_y: ['E (GPa)']
    compo_H_wo_outliers:
        filename: Compo_H_wo_outlier.csv
        columns_x: ['Zr_at','Nb_at','Mo_at','Ti_at','Cr_at']
        columns_y: ['H (GPa)']
    compo_CI:
        filename: Data_averaged.csv
        columns_x: ['Zr_at','Nb_at','Mo_at','Ti_at','Cr_at']
        columns_y: ['CI']
    compo_IQ:
        filename: Data_averaged.csv
        columns_x: ['Zr_at','Nb_at','Mo_at','Ti_at','Cr_at']
        columns_y: ['IQ']
        
        
models:
    keras-50x50:
        module: my_models
        function: get_keras_mpp
        args: { 'input_shape':[5], 'neurons':[50,50,1], 'activations':['relu','relu',None], 'optimizer':'adam', 'loss':'mse', 'metrics':['mse','mae','mape'] }
    
    keras-100x100:
        module: my_models
        function: get_keras_mpp
        args: { 'input_shape':[5], 'neurons':[100,100,1], 'activations':['relu','relu',None], 'optimizer':'adam', 'loss':'mse', 'metrics':['mse','mae','mape'] }
    
    keras-50x50x50:
        module: my_models
        function: get_keras_mpp
        args: { 'input_shape':[5], 'neurons':[50,50,50,1], 'activations':['relu','relu','relu',None], 'optimizer':'adam', 'loss':'mse', 'metrics':['mse','mae','mape'] }
    
    keras-100x100x100:
        module: my_models
        function: get_keras_mpp
        args: { 'input_shape':[5], 'neurons':[100,100,100,1], 'activations':['relu','relu','relu',None], 'optimizer':'adam', 'loss':'mse', 'metrics':['mse','mae','mape'] }
    
    keras-50x50x50x50:
        module: my_models
        function: get_keras_mpp
        args: { 'input_shape':[5], 'neurons':[50,50,50,50,1], 'activations':['relu','relu','relu','relu',None], 'optimizer':'adam', 'loss':'mse', 'metrics':['mse','mae','mape'] }
    
    keras-100x100x100x100:
        module: my_models
        function: get_keras_mpp
        args: { 'input_shape':[5], 'neurons':[100,100,100,100,1], 'activations':['relu','relu','relu','relu',None], 'optimizer':'adam', 'loss':'mse', 'metrics':['mse','mae','mape'] }
    
    keras-100x100x50x50:
        module: my_models
        function: get_keras_mpp
        args: { 'input_shape':[5], 'neurons':[100,100,50,50,1], 'activations':['relu','relu','relu','relu',None], 'optimizer':'adam', 'loss':'mse', 'metrics':['mse','mae','mape'] }
    
    keras-50x100x100x50:
        module: my_models
        function: get_keras_mpp
        args: { 'input_shape':[5], 'neurons':[50,100,100,50,1], 'activations':['relu','relu','relu','relu',None], 'optimizer':'adam', 'loss':'mse', 'metrics':['mse','mae','mape'] }
    
    keras-50x50x100x100:
        module: my_models
        function: get_keras_mpp
        args: { 'input_shape':[5], 'neurons':[50,50,100,100,1], 'activations':['relu','relu','relu','relu',None], 'optimizer':'adam', 'loss':'mse', 'metrics':['mse','mae','mape'] }
    


runs:

    Fit_E:
        description: Comparison of architecture on E
        datasets : [ 'compo_E_wo_outliers']
        models: [ 'keras-50x50','keras-100x100','keras-50x50x50','keras-100x100x100', 'keras-50x50x50x50', 'keras-100x100x100x100', 'keras-100x100x50x50','keras-50x100x100x50','keras-50x50x100x100']
        n_iters: [ 30 ]
        k_folds: [ 5 ]
        epochs: [ 200 ]
        batch_sizes: [ 8 ]
        seed: 123
        save_yytest: True 
   
    Fit_H:
        description: Comparison of architecture on H
        datasets: [ 'compo_H_wo_outliers']
        models: [ 'keras-50x50','keras-100x100','keras-50x50x50','keras-100x100x100', 'keras-50x50x50x50', 'keras-100x100x100x100', 'keras-100x100x50x50','keras-50x100x100x50','keras-50x50x100x100']
        n_iters: [ 30 ]
        k_folds: [ 5 ]
        epochs: [ 200 ]
        batch_sizes: [ 8 ]
        seed: 123
        save_yytest: True 
        
    Fit_CI:
        description: Comparison of architecture on CI
        datasets: [ 'compo_CI']
        models: [ 'keras-50x50','keras-100x100','keras-50x50x50','keras-100x100x100', 'keras-50x50x50x50', 'keras-100x100x100x100', 'keras-100x100x50x50','keras-50x100x100x50','keras-50x50x100x100']
        n_iters: [ 30 ]
        k_folds: [ 5 ]
        epochs: [ 200 ]
        batch_sizes: [ 8 ]
        seed: 123
        save_yytest: True 
    
    Fit_IQ:
        description: Comparison of architecture on IQ
        datasets: [ 'compo_IQ']
        models: [ 'keras-50x50','keras-100x100','keras-50x50x50','keras-100x100x100', 'keras-50x50x50x50', 'keras-100x100x100x100', 'keras-100x100x50x50','keras-50x100x100x50','keras-50x50x100x100']
        n_iters: [ 30 ]
        k_folds: [ 5 ]
        epochs: [ 200 ]
        batch_sizes: [ 8 ]
        seed: 123
        save_yytest: True 