# ------------------------------------------------------------------
#                  ____        _            _
#                 |  _ \ _   _| |_ ___ _ __| | __
#                 | |_) | | | | __/ _ \ '__| |/ /
#                 |  __/| |_| | ||  __/ |  |   <
#                 |_|    \__, |\__\___|_|  |_|\_\
#                        |___/                        Settings file
# ------------------------------------------------------------------
# Python Iterator for Kfold and co. - pjluc 2021
#
# This is a sample configuration
# 
# Note : Afin d'être portable, le paramètre datasets_dir peut être
#        forcé via une variable d'environnement.

global:
    description: Best classification models of NN, RF, SVM with all datasets
    settings v.: 1.0
    seed: 123
    datasets_dir: ./
    run_dir: ./campaign09cNN

datasets:
    
    compo_CI_class:
        filename: Data_averaged.csv
        columns_x: ['Zr_at','Nb_at','Mo_at','Ti_at','Cr_at']
        columns_y: ['Phase class (0: amorphous)']
        
    compo_DRX_class:
        filename: Database_XRD.csv
        columns_x: ['Zr_at','Nb_at','Mo_at','Ti_at','Cr_at']
        columns_y: ['XRD (0: amorphous)']
        
        
models:
# Classification
    # NN class EBSD and XRD   
    keras-50x50x100x100:
        module: my_models
        function: get_keras_mpp
        args: { 'input_shape':[5], 'neurons':[50,50,100,100,1], 'activations':['relu','relu','relu','relu','sigmoid'], 'optimizer':'adam', 'loss':'binary_crossentropy', 'metrics':['accuracy','binary_crossentropy'] }    
        


runs:

    Class_EBSD:
        description: Comparison of architecture on EBSD class
        datasets : [ 'compo_CI_class']
        models: [ 'keras-50x50x100x100']
        n_iters: [ 30 ]
        k_folds: [ 5 ]
        epochs: [ 200 ]
        batch_sizes: [ 8 ]
        seed: 123
        save_yytest: True 
        predict_type: sigmoid
   
    Class_XRD:
        description: Comparison of architecture on XRD class
        datasets: [ 'compo_DRX_class']
        models: [ 'keras-50x50x100x100']
        n_iters: [ 30 ]
        k_folds: [ 5 ]
        epochs: [ 200 ]
        batch_sizes: [ 8 ]
        seed: 123
        save_yytest: True 
        predict_type: sigmoid