# ------------------------------------------------------------------
#                  ____        _            _
#                 |  _ \ _   _| |_ ___ _ __| | __
#                 | |_) | | | | __/ _ \ '__| |/ /
#                 |  __/| |_| | ||  __/ |  |   <
#                 |_|    \__, |\__\___|_|  |_|\_\
#                        |___/                        Settings file
# ------------------------------------------------------------------
# Python Iterator for Kfold and co. - pjluc 2021
#
# This is a sample configuration
# 
# Note : Afin d'être portable, le paramètre datasets_dir peut être
#        forcé via une variable d'environnement.

global:
    description: Test of random forrest architecture.
    settings v.: 1.0
    seed: 123
    datasets_dir: ./
    run_dir: ./campaign08/RF_r

datasets:
    
    compo_E_wo_outliers:
        filename: Compo_E_wo_outlier.csv
        columns_x: ['Zr_at','Nb_at','Mo_at','Ti_at','Cr_at']
        columns_y: ['E (GPa)']
    compo_H_wo_outliers:
        filename: Compo_H_wo_outlier.csv
        columns_x: ['Zr_at','Nb_at','Mo_at','Ti_at','Cr_at']
        columns_y: ['H (GPa)']
    compo_CI:
        filename: Data_averaged.csv
        columns_x: ['Zr_at','Nb_at','Mo_at','Ti_at','Cr_at']
        columns_y: ['CI']
    compo_IQ:
        filename: Data_averaged.csv
        columns_x: ['Zr_at','Nb_at','Mo_at','Ti_at','Cr_at']
        columns_y: ['IQ']
        
models:
  
    sklearn-rfr-50-5:
        module: sklearn.ensemble
        class: RandomForestRegressor
        args: { 'n_estimators':50 , 'criterion':'mae', 'min_samples_split':5}
        
    sklearn-rfr-100-5:
        module: sklearn.ensemble
        class: RandomForestRegressor
        args: { 'n_estimators':100 ,  'criterion':'mae', 'min_samples_split':5}

    sklearn-rfr-150-5:
        module: sklearn.ensemble
        class: RandomForestRegressor
        args: { 'n_estimators':150 ,  'criterion':'mae', 'min_samples_split':5} 
        
        
    sklearn-rfr-50-10:
        module: sklearn.ensemble
        class: RandomForestRegressor
        args: { 'n_estimators':50 , 'criterion':'mae', 'min_samples_split':10}
        
    sklearn-rfr-100-10:
        module: sklearn.ensemble
        class: RandomForestRegressor
        args: { 'n_estimators':100 ,  'criterion':'mae', 'min_samples_split':10}

    sklearn-rfr-150-10:
        module: sklearn.ensemble
        class: RandomForestRegressor
        args: { 'n_estimators':150 ,  'criterion':'mae', 'min_samples_split':10} 
        
        
    sklearn-rfr-50-20:
        module: sklearn.ensemble
        class: RandomForestRegressor
        args: { 'n_estimators':50 , 'criterion':'mae', 'min_samples_split':20}
        
    sklearn-rfr-100-20:
        module: sklearn.ensemble
        class: RandomForestRegressor
        args: { 'n_estimators':100 ,  'criterion':'mae', 'min_samples_split':20}

    sklearn-rfr-150-20:
        module: sklearn.ensemble
        class: RandomForestRegressor
        args: { 'n_estimators':150 ,  'criterion':'mae', 'min_samples_split':20}        
        
runs:

    Fit_E:
        description: Comparison of architecture on E
        datasets: [ 'compo_E_wo_outliers']
        models: [ 'sklearn-rfr-50-5','sklearn-rfr-100-5','sklearn-rfr-150-5','sklearn-rfr-50-10','sklearn-rfr-100-10','sklearn-rfr-150-10','sklearn-rfr-50-20','sklearn-rfr-100-20','sklearn-rfr-150-20']
        n_iters: [ 30 ]
        k_folds: [ 5 ]
        epochs: [ 200 ]
        batch_sizes: [ 8 ]
        seed: 123
        save_yytest: True 
   
    Fit_H:
        description: Comparison of architecture on E
        datasets: [ 'compo_H_wo_outliers']
        models: [ 'sklearn-rfr-50-5','sklearn-rfr-100-5','sklearn-rfr-150-5','sklearn-rfr-50-10','sklearn-rfr-100-10','sklearn-rfr-150-10','sklearn-rfr-50-20','sklearn-rfr-100-20','sklearn-rfr-150-20']
        n_iters: [ 30 ]
        k_folds: [ 5 ]
        epochs: [ 200 ]
        batch_sizes: [ 8 ]
        seed: 123
        save_yytest: True 
        
    Fit_CI:
        description: Comparison of architecture on E
        datasets: [ 'compo_CI']
        models: [ 'sklearn-rfr-50-5','sklearn-rfr-100-5','sklearn-rfr-150-5','sklearn-rfr-50-10','sklearn-rfr-100-10','sklearn-rfr-150-10','sklearn-rfr-50-20','sklearn-rfr-100-20','sklearn-rfr-150-20']
        n_iters: [ 30 ]
        k_folds: [ 5 ]
        epochs: [ 200 ]
        batch_sizes: [ 8 ]
        seed: 123
        save_yytest: True 
    
    Fit_IQ:
        description: Comparison of architecture on E
        datasets: [ 'compo_IQ']
        models: [ 'sklearn-rfr-50-5','sklearn-rfr-100-5','sklearn-rfr-150-5','sklearn-rfr-50-10','sklearn-rfr-100-10','sklearn-rfr-150-10','sklearn-rfr-50-20','sklearn-rfr-100-20','sklearn-rfr-150-20']
        n_iters: [ 30 ]
        k_folds: [ 5 ]
        epochs: [ 200 ]
        batch_sizes: [ 8 ]
        seed: 123
        save_yytest: True 