# ------------------------------------------------------------------
#                  ____        _            _
#                 |  _ \ _   _| |_ ___ _ __| | __
#                 | |_) | | | | __/ _ \ '__| |/ /
#                 |  __/| |_| | ||  __/ |  |   <
#                 |_|    \__, |\__\___|_|  |_|\_\
#                        |___/                        Settings file
# ------------------------------------------------------------------
# Python Iterator for Kfold and co. - pjluc 2021
#
# This is a sample configuration
# 
# Note : Afin d'être portable, le paramètre datasets_dir peut être
#        forcé via une variable d'environnement.

global:
    description: Test of random forrest architecture.
    settings v.: 1.0
    seed: 123
    datasets_dir: ./
    run_dir: ./campaign08/RF_c

datasets:
    
    compo_CI_class:
        filename: Data_averaged.csv
        columns_x: ['Zr_at','Nb_at','Mo_at','Ti_at','Cr_at']
        columns_y: ['Phase class (0: amorphous)']
    compo_DRX_class:
        filename: Database_XRD.csv
        columns_x: ['Zr_at','Nb_at','Mo_at','Ti_at','Cr_at']
        columns_y: ['XRD (0: amorphous)']
         
models:
  
    sklearn-rfr-50-5:
        module: sklearn.ensemble
        class: RandomForestClassifier
        args: { 'n_estimators':50 ,  'criterion':'entropy','min_samples_split':5}
        
    sklearn-rfr-100-5:
        module: sklearn.ensemble
        class: RandomForestClassifier
        args: { 'n_estimators':100 ,  'criterion':'entropy', 'min_samples_split':5}

    sklearn-rfr-150-5:
        module: sklearn.ensemble
        class: RandomForestClassifier
        args: { 'n_estimators':150 ,  'criterion':'entropy', 'min_samples_split':5} 
        
        
    sklearn-rfr-50-10:
        module: sklearn.ensemble
        class: RandomForestClassifier
        args: { 'n_estimators':50 , 'criterion':'entropy', 'min_samples_split':10}
        
    sklearn-rfr-100-10:
        module: sklearn.ensemble
        class: RandomForestClassifier
        args: { 'n_estimators':100 ,  'criterion':'entropy', 'min_samples_split':10}

    sklearn-rfr-150-10:
        module: sklearn.ensemble
        class: RandomForestClassifier
        args: { 'n_estimators':150 ,  'criterion':'entropy', 'min_samples_split':10} 
        
        
    sklearn-rfr-50-20:
        module: sklearn.ensemble
        class: RandomForestClassifier
        args: { 'n_estimators':50 , 'criterion':'entropy', 'min_samples_split':20}
        
    sklearn-rfr-100-20:
        module: sklearn.ensemble
        class: RandomForestClassifier
        args: { 'n_estimators':100 ,  'criterion':'entropy', 'min_samples_split':20}

    sklearn-rfr-150-20:
        module: sklearn.ensemble
        class: RandomForestClassifier
        args: { 'n_estimators':150 ,  'criterion':'entropy', 'min_samples_split':20}        
        
runs:

    Class_CI:
        description: Comparison of architecture on CI class
        datasets : [ 'compo_CI_class']
        models: [ 'sklearn-rfr-50-5','sklearn-rfr-100-5','sklearn-rfr-150-5','sklearn-rfr-50-10','sklearn-rfr-100-10','sklearn-rfr-150-10','sklearn-rfr-50-20','sklearn-rfr-100-20','sklearn-rfr-150-20']
        n_iters: [ 30 ]
        k_folds: [ 5 ]
        epochs: [ 200 ]
        batch_sizes: [ 8 ]
        seed: 123
        save_yytest: True
        predict_type: classes
   
    Class_DRX:
        description: Comparison of architecture on DRX class
        datasets: [ 'compo_DRX_class']
        models: [ 'sklearn-rfr-50-5','sklearn-rfr-100-5','sklearn-rfr-150-5','sklearn-rfr-50-10','sklearn-rfr-100-10','sklearn-rfr-150-10','sklearn-rfr-50-20','sklearn-rfr-100-20','sklearn-rfr-150-20']
        n_iters: [ 30 ]
        k_folds: [ 5 ]
        epochs: [ 200 ]
        batch_sizes: [ 8 ]
        seed: 123
        save_yytest: True
        predict_type: classes
        
   