# ------------------------------------------------------------------
#                  ____        _            _
#                 |  _ \ _   _| |_ ___ _ __| | __
#                 | |_) | | | | __/ _ \ '__| |/ /
#                 |  __/| |_| | ||  __/ |  |   <
#                 |_|    \__, |\__\___|_|  |_|\_\
#                        |___/                        Settings file
# ------------------------------------------------------------------
# Python Iterator for Kfold and co. - pjluc 2021
#
# This is a sample configuration
# 
# Note : Afin d'être portable, le paramètre datasets_dir peut être
#        forcé via une variable d'environnement.

global:
    description: Test of neural network architecture.
    settings v.: 1.0
    seed: 123
    datasets_dir: ./
    run_dir: ./campaign08/NN_c


datasets:
    
    compo_CI_class:
        filename: Data_averaged.csv
        columns_x: ['Zr_at','Nb_at','Mo_at','Ti_at','Cr_at']
        columns_y: ['Phase class (0: amorphous)']
    compo_DRX_class:
        filename: Database_XRD.csv
        columns_x: ['Zr_at','Nb_at','Mo_at','Ti_at','Cr_at']
        columns_y: ['XRD (0: amorphous)']
   
        
models:
    keras-50x50:
        module: my_models
        function: get_keras_mpp
        args: { 'input_shape':[5], 'neurons':[50,50,1], 'activations':['relu','relu','sigmoid'], 'optimizer':'adam', 'loss':'binary_crossentropy', 'metrics':['accuracy','binary_crossentropy'] }
    
    keras-100x100:
        module: my_models
        function: get_keras_mpp
        args: { 'input_shape':[5], 'neurons':[100,100,1], 'activations':['relu','relu','sigmoid'], 'optimizer':'adam', 'loss':'binary_crossentropy', 'metrics':['accuracy','binary_crossentropy'] }
    
    keras-50x50x50:
        module: my_models
        function: get_keras_mpp
        args: { 'input_shape':[5], 'neurons':[50,50,50,1], 'activations':['relu','relu','relu','sigmoid'], 'optimizer':'adam', 'loss':'binary_crossentropy', 'metrics':['accuracy','binary_crossentropy'] }
    
    keras-100x100x100:
        module: my_models
        function: get_keras_mpp
        args: { 'input_shape':[5], 'neurons':[100,100,100,1], 'activations':['relu','relu','relu','sigmoid'], 'optimizer':'adam', 'loss':'binary_crossentropy', 'metrics':['accuracy','binary_crossentropy'] }
    
    keras-50x50x50x50:
        module: my_models
        function: get_keras_mpp
        args: { 'input_shape':[5], 'neurons':[50,50,50,50,1], 'activations':['relu','relu','relu','relu','sigmoid'], 'optimizer':'adam', 'loss':'binary_crossentropy', 'metrics':['accuracy','binary_crossentropy'] }
    
    keras-100x100x100x100:
        module: my_models
        function: get_keras_mpp
        args: { 'input_shape':[5], 'neurons':[100,100,100,100,1], 'activations':['relu','relu','relu','relu','sigmoid'], 'optimizer':'adam', 'loss':'binary_crossentropy', 'metrics':['accuracy','binary_crossentropy'] }
    
    keras-100x100x50x50:
        module: my_models
        function: get_keras_mpp
        args: { 'input_shape':[5], 'neurons':[100,100,50,50,1], 'activations':['relu','relu','relu','relu','sigmoid'], 'optimizer':'adam', 'loss':'binary_crossentropy', 'metrics':['accuracy','binary_crossentropy'] }
    
    keras-50x100x100x50:
        module: my_models
        function: get_keras_mpp
        args: { 'input_shape':[5], 'neurons':[50,100,100,50,1], 'activations':['relu','relu','relu','relu','sigmoid'], 'optimizer':'adam', 'loss':'binary_crossentropy', 'metrics':['accuracy','binary_crossentropy'] }
    
    keras-50x50x100x100:
        module: my_models
        function: get_keras_mpp
        args: { 'input_shape':[5], 'neurons':[50,50,100,100,1], 'activations':['relu','relu','relu','relu','sigmoid'], 'optimizer':'adam', 'loss':'binary_crossentropy', 'metrics':['accuracy','binary_crossentropy'] }
    


runs:

    Class_CI:
        description: Comparison of architecture on CI class
        datasets : [ 'compo_CI_class']
        models: [ 'keras-50x50','keras-100x100','keras-50x50x50','keras-100x100x100', 'keras-50x50x50x50', 'keras-100x100x100x100', 'keras-100x100x50x50','keras-50x100x100x50','keras-50x50x100x100']
        n_iters: [ 30 ]
        k_folds: [ 5 ]
        epochs: [ 200 ]
        batch_sizes: [ 8 ]
        seed: 123
        save_yytest: True
   
    Class_DRX:
        description: Comparison of architecture on DRX class
        datasets: [ 'compo_DRX_class']
        models: [ 'keras-50x50','keras-100x100','keras-50x50x50','keras-100x100x100', 'keras-50x50x50x50', 'keras-100x100x100x100', 'keras-100x100x50x50','keras-50x100x100x50','keras-50x50x100x100']
        n_iters: [ 30 ]
        k_folds: [ 5 ]
        epochs: [ 200 ]
        batch_sizes: [ 8 ]
        seed: 123
        save_yytest: True
        
    